default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: rails_devise_token_auth_development
test:
  <<: *default
  database: rails_devise_token_auth_test
  
production:
  <<: *default
  database: rails_devise_token_auth_production
